//! Lean Proof Domain Adapter for NPE
//!
//! This adapter allows the NPE to generate Lean proof candidates,
//! then verifies them through Lean.
//!
//! The pipeline is:
//!   NPE generates proof attempts
//!   → Lean/RV verification
//!   → Genesis metrics  
//!   → Formation admission
//!   → Best verified proof selected

use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// Get current timestamp as i64 (seconds since epoch)
fn current_timestamp() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

/// Get current timestamp as RFC3339 string
fn current_timestamp_rfc3339() -> String {
    // Simple ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
    let now = current_timestamp();
    // Convert to a simple format (this is sufficient for audit purposes)
    format!("{}", now)
}

/// Proof candidate generated by the NPE
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProofCandidate {
    pub id: String,
    pub wildness: f64,
    pub target_theorem: String,
    pub proof_text: String,
    pub proof_tactics: Vec<String>,
    pub tactic_count: usize,
    pub helper_lemmas: usize,
    pub imports: Vec<String>,
    pub novelty: f64,
}

/// Lean verification report
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LeanVerificationReport {
    pub compiles: bool,
    pub has_sorry: bool,
    pub has_admit: bool,
    pub new_axioms: usize,
    pub statement_unchanged: bool,
    pub forbidden_imports: bool,

    pub build_time_ms: u64,
    pub errors: Vec<String>,
    pub warnings: usize,

    pub genesis_margin: i128,
    pub coherence_margin: i128,
    pub formation_accept: bool,
    /// Detailed failure report
    pub failure_report: Option<crate::failure_taxonomy::FailureReport>,
}

/// Compute Genesis metrics for a proof
pub fn compute_genesis_metrics(candidate: &ProofCandidate) -> (u128, u128, u128) {
    // M(t'): proof complexity after
    let proof_complexity = compute_proof_complexity(candidate);

    // C(p): generation cost
    let cost = candidate.tactic_count as u128 * 5
        + candidate.helper_lemmas as u128 * 20
        + candidate.imports.len() as u128 * 10;

    // D(p): defect budget based on wildness
    let defect = 50 + (candidate.wildness * 10.0) as u128;

    (proof_complexity, cost, defect)
}

/// Compute proof complexity
fn compute_proof_complexity(candidate: &ProofCandidate) -> u128 {
    let mut complexity = 0u128;

    // Base complexity from proof length
    complexity += candidate.proof_text.len() as u128;

    // Add weight for tactics
    complexity += candidate.tactic_count as u128 * 10;

    // Add helper lemma complexity
    complexity += candidate.helper_lemmas as u128 * 30;

    // Add import complexity
    complexity += candidate.imports.len() as u128 * 50;

    // Penalize "sorry" usage heavily
    if candidate.proof_text.contains("sorry") {
        complexity += 1000;
    }

    // Penalize "admit" usage
    if candidate.proof_text.contains("admit") {
        complexity += 500;
    }

    complexity
}

/// Compute Coherence metrics for a proof
pub fn compute_coherence_metrics(report: &LeanVerificationReport) -> (u128, u128, u128) {
    // V(y): post-proof risk
    let mut risk = 0u128;
    if !report.compiles {
        risk += 100;
    }
    if report.has_sorry {
        risk += 500;
    }
    if report.has_admit {
        risk += 300;
    }
    risk += report.new_axioms as u128 * 100;
    if report.forbidden_imports {
        risk += 200;
    }
    risk += report.warnings as u128 * 2;

    // Spend(R): execution cost
    let spend = (report.build_time_ms / 100) as u128;

    // Defect(R): allowed budget
    let defect = 50; // base budget

    (risk, spend, defect)
}

/// Check if candidate is formation-admissible
pub fn is_formation_admissible(
    candidate: &ProofCandidate,
    base_complexity: u128,
    report: &LeanVerificationReport,
) -> (bool, i128, i128) {
    let (m_after, cost, defect) = compute_genesis_metrics(candidate);
    let genesis_margin = base_complexity as i128 + defect as i128 - m_after as i128 - cost as i128;

    let (risk, spend, def) = compute_coherence_metrics(report);
    let coherence_margin = risk as i128 + def as i128 - spend as i128;

    let formation_accept = genesis_margin >= 0
        && report.compiles
        && !report.has_sorry
        && !report.has_admit
        && !report.forbidden_imports
        && coherence_margin >= 0;

    (formation_accept, genesis_margin, coherence_margin)
}

/// First failure classification for proofs
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProofFirstFailure {
    Accepted,
    Genesis,
    Compiles,
    Sorry,
    Admit,
    StatementChanged,
    ForbiddenImport,
    Coherence,
}

impl ProofFirstFailure {
    pub fn classify(
        genesis_margin: i128,
        report: &LeanVerificationReport,
        coherence_margin: i128,
    ) -> Self {
        // First check Genesis
        if genesis_margin < 0 {
            return ProofFirstFailure::Genesis;
        }
        // Then verification checks
        if !report.compiles {
            return ProofFirstFailure::Compiles;
        }
        if report.has_sorry {
            return ProofFirstFailure::Sorry;
        }
        if report.has_admit {
            return ProofFirstFailure::Admit;
        }
        if !report.statement_unchanged {
            return ProofFirstFailure::StatementChanged;
        }
        if report.forbidden_imports {
            return ProofFirstFailure::ForbiddenImport;
        }
        // Finally check Coherence
        if coherence_margin < 0 {
            return ProofFirstFailure::Coherence;
        }
        ProofFirstFailure::Accepted
    }
}

/// Proof policy configuration
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProofPolicy {
    pub allow_sorry: bool,
    pub allow_admit: bool,
    pub allow_new_axioms: bool,
    pub allow_forbidden_imports: bool,
    pub max_tactic_count: usize,
    pub max_helper_lemmas: usize,
    pub max_proof_length: usize,
}

impl Default for ProofPolicy {
    fn default() -> Self {
        ProofPolicy {
            allow_sorry: false,
            allow_admit: false,
            allow_new_axioms: false,
            allow_forbidden_imports: false,
            max_tactic_count: 100,
            max_helper_lemmas: 10,
            max_proof_length: 5000,
        }
    }
}

/// Proof selection mode
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProofSelectorMode {
    /// Maximizes novelty with safety margin
    SafeNovel,
    /// Maximizes novelty near boundary
    Edge,
    /// Finds near-boundary still-admissible
    NearBoundary,
}

/// Formation result for proofs
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProofFormationResult {
    pub candidate_id: String,
    pub formation_accept: bool,
    pub first_failure: ProofFirstFailure,

    pub genesis_margin: i128,
    pub coherence_margin: i128,
    pub boundary_margin: i128,

    pub novelty: f64,
    pub safe_score: f64,
    pub edge_score: f64,

    pub report: LeanVerificationReport,
}

/// Build formation result for a proof
pub fn build_formation_result(
    candidate: &ProofCandidate,
    base_complexity: u128,
    report: &LeanVerificationReport,
    _mode: &ProofSelectorMode,
    alpha: f64,
) -> ProofFormationResult {
    let (m_after, cost, defect) = compute_genesis_metrics(candidate);
    let genesis_margin = base_complexity as i128 + defect as i128 - m_after as i128 - cost as i128;

    let (risk, spend, def) = compute_coherence_metrics(report);
    let coherence_margin = risk as i128 + def as i128 - spend as i128;

    let boundary_margin = genesis_margin.min(coherence_margin);

    let safe_score = candidate.novelty + alpha * boundary_margin as f64;
    let edge_score = candidate.novelty - alpha * boundary_margin as f64;

    let formation_accept = genesis_margin >= 0
        && report.compiles
        && !report.has_sorry
        && !report.has_admit
        && coherence_margin >= 0;

    let first_failure = ProofFirstFailure::classify(genesis_margin, report, coherence_margin);

    ProofFormationResult {
        candidate_id: candidate.id.clone(),
        formation_accept,
        first_failure,
        genesis_margin,
        coherence_margin,
        boundary_margin,
        novelty: candidate.novelty,
        safe_score,
        edge_score,
        report: report.clone(),
    }
}

/// Proof class selection for diverse generation
#[derive(Clone, Debug, PartialEq)]
pub enum ProofClass {
    Direct,        // direct tactic application
    HelperLemma,   // adds helper lemmas
    Simplify,      // adds simp/rw lemmas
    Cases,         // adds cases/hypothesis
    Induction,     // adds induction
    LibrarySearch, // imports from Mathlib
    Weaken,        // uses sorry/admit
    Refactor,      // refactors existing proof
}

/// Lean error kinds parsed from Lean output
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum LeanErrorKind {
    /// No error
    None,
    /// Too many arguments for function
    TooManyArguments,
    /// Unknown identifier
    UnknownIdentifier,
    /// Type mismatch
    TypeMismatch,
    /// Invalid binder
    InvalidBinder,
    /// Goal incomplete
    GoalIncomplete,
    /// Tactic failed
    TacticFailed,
    /// File not found
    FileNotFound,
    /// Parse error
    ParseError,
    /// Universe level error
    UniverseLevelError,
    /// Authority error (forbidden import)
    AuthorityError,
    /// Unknown error
    Unknown(String),
}

impl LeanErrorKind {
    /// Parse Lean error output into structured error kind
    pub fn parse(error_output: &str) -> Self {
        let output_lower = error_output.to_lowercase();

        // Check for specific error patterns in order of specificity
        if output_lower.contains("too many arguments") {
            LeanErrorKind::TooManyArguments
        } else if output_lower.contains("unknown identifier")
            || output_lower.contains("unknown function")
            || output_lower.contains("unknown constant")
        {
            LeanErrorKind::UnknownIdentifier
        } else if output_lower.contains("type mismatch")
            || output_lower.contains("type error")
            || output_lower.contains("expected") && output_lower.contains("got")
        {
            LeanErrorKind::TypeMismatch
        } else if output_lower.contains("invalid binder") || output_lower.contains("invalid type") {
            LeanErrorKind::InvalidBinder
        } else if output_lower.contains("goal is not")
            || output_lower.contains(" Tactics failed")
            || output_lower.contains("tactic failed")
        {
            LeanErrorKind::GoalIncomplete
        } else if output_lower.contains("file not found")
            || output_lower.contains("could not find file")
            || output_lower.contains("invalid path")
        {
            LeanErrorKind::FileNotFound
        } else if output_lower.contains("parse error")
            || output_lower.contains("unexpected token")
            || output_lower.contains("syntax error")
        {
            LeanErrorKind::ParseError
        } else if output_lower.contains("universe") || output_lower.contains("level") {
            LeanErrorKind::UniverseLevelError
        } else if output_lower.contains("import")
            || output_lower.contains("authority")
            || output_lower.contains("forbidden")
        {
            LeanErrorKind::AuthorityError
        } else if error_output.trim().is_empty() {
            LeanErrorKind::None
        } else if output_lower.contains("failed")
            || output_lower.contains("error")
            || output_lower.contains("invalid")
        {
            LeanErrorKind::Unknown(error_output.to_string())
        } else {
            LeanErrorKind::None
        }
    }

    /// Returns true if this error is retryable (might pass with different tactic)
    pub fn is_retryable(&self) -> bool {
        matches!(
            self,
            LeanErrorKind::GoalIncomplete
                | LeanErrorKind::TacticFailed
                | LeanErrorKind::TypeMismatch
                | LeanErrorKind::UnknownIdentifier
        )
    }
}

/// PatchTransaction for safe Lean proof repairs
/// Tests all repairs in temp files before committing to real files
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PatchTransaction {
    pub id: String,
    pub target_file: PathBuf,
    pub temp_file: PathBuf,
    pub original_content: String,
    pub proposed_patch: String,
    pub status: PatchTransactionStatus,
    pub verified_at: Option<i64>,
    pub errors: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum PatchTransactionStatus {
    Pending,
    Testing,
    Verified,
    Failed,
    Committed,
    RolledBack,
}

impl PatchTransaction {
    /// Create a new patch transaction
    pub fn new(
        id: String,
        target_file: PathBuf,
        temp_dir: PathBuf,
        original_content: String,
        proposed_patch: String,
    ) -> Self {
        let temp_file = temp_dir.join(format!("_repair_temp_{}.lean", id));

        PatchTransaction {
            id,
            target_file,
            temp_file,
            original_content,
            proposed_patch,
            status: PatchTransactionStatus::Pending,
            verified_at: None,
            errors: vec![],
        }
    }

    /// Write patch to temp file for isolated testing
    pub fn write_temp_file(&self) -> Result<(), std::io::Error> {
        use std::fs;
        use std::io::Write;

        let mut file = fs::File::create(&self.temp_file)?;
        file.write_all(self.proposed_patch.as_bytes())?;
        Ok(())
    }

    /// Mark transaction as verified (passed Lean verification)
    pub fn mark_verified(&mut self) {
        self.status = PatchTransactionStatus::Verified;
        self.verified_at = Some(current_timestamp());
    }

    /// Mark transaction as failed
    pub fn mark_failed(&mut self, error: String) {
        self.status = PatchTransactionStatus::Failed;
        self.errors.push(error);
    }

    /// Commit the verified patch to the original file
    pub fn commit(&self) -> Result<(), std::io::Error> {
        use std::fs;
        use std::io::Write;

        let mut file = fs::File::create(&self.target_file)?;
        file.write_all(self.proposed_patch.as_bytes())?;
        Ok(())
    }

    /// Clean up temp file
    pub fn cleanup(&self) -> Result<(), std::io::Error> {
        use std::fs;

        if self.temp_file.exists() {
            fs::remove_file(&self.temp_file)?;
        }
        Ok(())
    }
}

/// Transaction log for maintaining rollback safety
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct TransactionLog {
    pub transactions: Vec<TransactionEntry>,
    pub committed_count: usize,
    pub failed_count: usize,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TransactionEntry {
    pub transaction_id: String,
    pub target_file: String,
    pub status: PatchTransactionStatus,
    pub timestamp: i64,
    pub error: Option<String>,
}

impl TransactionLog {
    /// Log a committed transaction
    pub fn log_commit(&mut self, tx: &PatchTransaction) {
        self.transactions.push(TransactionEntry {
            transaction_id: tx.id.clone(),
            target_file: tx.target_file.to_string_lossy().to_string(),
            status: PatchTransactionStatus::Committed,
            timestamp: current_timestamp(),
            error: None,
        });
        self.committed_count += 1;
    }

    /// Log a failed transaction
    pub fn log_failure(&mut self, tx: &PatchTransaction, error: String) {
        self.transactions.push(TransactionEntry {
            transaction_id: tx.id.clone(),
            target_file: tx.target_file.to_string_lossy().to_string(),
            status: PatchTransactionStatus::Failed,
            timestamp: current_timestamp(),
            error: Some(error),
        });
        self.failed_count += 1;
    }
}

impl ProofClass {
    pub fn select(wildness: f64, rand: f64) -> Self {
        if wildness < 0.5 {
            if rand < 0.7 {
                ProofClass::Direct
            } else {
                ProofClass::Refactor
            }
        } else if wildness < 1.5 {
            if rand < 0.5 {
                ProofClass::Direct
            } else if rand < 0.8 {
                ProofClass::HelperLemma
            } else {
                ProofClass::Refactor
            }
        } else if wildness < 2.5 {
            if rand < 0.3 {
                ProofClass::Direct
            } else if rand < 0.5 {
                ProofClass::HelperLemma
            } else if rand < 0.7 {
                ProofClass::Simplify
            } else if rand < 0.85 {
                ProofClass::Induction
            } else if rand < 0.95 {
                ProofClass::LibrarySearch
            } else {
                ProofClass::Weaken
            }
        } else {
            // High wildness - more aggressive
            if rand < 0.2 {
                ProofClass::HelperLemma
            } else if rand < 0.4 {
                ProofClass::Cases
            } else if rand < 0.6 {
                ProofClass::Induction
            } else if rand < 0.8 {
                ProofClass::LibrarySearch
            } else {
                ProofClass::Weaken
            }
        }
    }
}

/// Benchmark audit JSON snapshot for tracking CTRL evolution
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BenchmarkAudit {
    pub timestamp: String,
    pub session_id: String,
    pub attempts: Vec<AttemptRecord>,
    pub candidates: Vec<CandidateRecord>,
    pub accepted: Vec<AcceptedRecord>,
    pub metrics: BenchmarkMetrics,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AttemptRecord {
    pub attempt_id: String,
    pub target_theorem: String,
    pub candidate_id: String,
    pub timestamp: i64,
    pub result: AttemptResult,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum AttemptResult {
    Success,
    Failed(String),
    Timeout,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CandidateRecord {
    pub candidate_id: String,
    pub proof_text: String,
    pub wildness: f64,
    pub novelty: f64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AcceptedRecord {
    pub candidate_id: String,
    pub commit_hash: String,
    pub timestamp: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct BenchmarkMetrics {
    pub total_attempts: usize,
    pub successful_attempts: usize,
    pub failed_attempts: usize,
    pub avg_wildness: f64,
    pub avg_novelty: f64,
    pub total_time_ms: u64,
}

impl BenchmarkAudit {
    /// Record an attempt
    pub fn record_attempt(&mut self, attempt: AttemptRecord) {
        self.attempts.push(attempt.clone());
        self.metrics.total_attempts += 1;
        match attempt.result {
            AttemptResult::Success => self.metrics.successful_attempts += 1,
            AttemptResult::Failed(_) | AttemptResult::Timeout => self.metrics.failed_attempts += 1,
        }
    }

    /// Serialize to JSON
    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(self).unwrap_or_default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_genesis_metrics() {
        let candidate = ProofCandidate {
            id: "proof-1".to_string(),
            wildness: 1.0,
            target_theorem: "target".to_string(),
            proof_text: "apply h1".to_string(),
            proof_tactics: vec!["apply".to_string()],
            tactic_count: 1,
            helper_lemmas: 0,
            imports: vec![],
            novelty: 1.0,
        };

        let (m_after, cost, _) = compute_genesis_metrics(&candidate);
        assert!(m_after > 0);
        assert!(cost > 0);
    }

    #[test]
    fn test_formation_admissible() {
        let candidate = ProofCandidate {
            id: "proof-1".to_string(),
            wildness: 1.0,
            target_theorem: "target".to_string(),
            proof_text: "exact dec_trivial".to_string(),
            proof_tactics: vec!["exact".to_string()],
            tactic_count: 1,
            helper_lemmas: 0,
            imports: vec![],
            novelty: 1.0,
        };

        let report = LeanVerificationReport {
            compiles: true,
            has_sorry: false,
            has_admit: false,
            new_axioms: 0,
            statement_unchanged: true,
            forbidden_imports: false,
            build_time_ms: 500,
            errors: vec![],
            warnings: 0,
            genesis_margin: 0,
            coherence_margin: 0,
            formation_accept: false,
            failure_report: None,
        };

        let (accept, gen_m, _) = is_formation_admissible(&candidate, 1000, &report);
        assert!(accept);
        assert!(gen_m > 0);
    }
}
