use crate::gauge::CohGaugeField;
use coh_core::atom::CohAtom;
use coh_core::cohbit::CohBit;
use num_traits::ToPrimitive;
use serde::{Deserialize, Serialize};

/// Coh Field: A collection of interacting Coh Atoms.
///
/// \boxed{ \text{Coh Field} = \text{distribution of Coh Atoms } \rho_t(x) }
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CohField {
    pub atoms: Vec<CohAtom>,
    pub global_gauge: CohGaugeField,
    pub coupling_constant: f64,
}

impl CohField {
    pub fn new(coupling: f64) -> Self {
        Self {
            atoms: vec![],
            global_gauge: CohGaugeField::new(3), // SU(2) or SU(3) scaffold
            coupling_constant: coupling,
        }
    }

    /// Interaction Energy: V_int = g * Tr(J_i * A_j)
    /// This represents the "interference" or "coordination" cost between agents.
    pub fn interaction_cost(&self, atom_i: &CohAtom, bit_i: &CohBit) -> f64 {
        // Current of the proposed transition
        // (In a real field, this would involve the gauge generated by other atoms)
        let _current_i = bit_i.valuation_post.to_f64().unwrap_or(0.0);

        // Simplified coupling: sum of neighbor densities * coupling
        let neighbor_density: f64 = self
            .atoms
            .iter()
            .filter(|a| a.state_hash != atom_i.state_hash)
            .map(|a| a.valuation.to_f64().unwrap_or(0.0))
            .sum();

        self.coupling_constant * neighbor_density
    }

    /// Step the entire field: Each atom selects its optimal bit accounting for global coupling.
    pub fn step(&mut self, lambda: f64) -> Vec<(usize, String)> {
        let mut transitions = vec![];

        // We clone indices to avoid borrow checker conflicts during evolution
        for i in 0..self.atoms.len() {
            // Compute interaction term for this atom
            // (In a real system, this would be a full potential sweep)
            let int_cost = 0.1; // Placeholder for sum over neighbors

            if let Some(optimal_bit) = self.atoms[i].select_optimal_bit(lambda, int_cost).cloned() {
                transitions.push((i, optimal_bit.transition_id.clone()));
                // Evolve the atom
                self.atoms[i].evolve(&optimal_bit, lambda, int_cost);
            }
        }

        transitions
    }
}
