//! NPE Rust Upgrade Loop - Real File Testing
//!
//! This example generates REAL code patches and tests them against actual Rust files.

use std::fs;
use std::path::Path;
use std::process::Command;

/// Simple RNG
#[derive(Clone, Debug)]
struct SimpleRng {
    state: u64,
}

impl SimpleRng {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }
    fn next(&mut self) -> u64 {
        self.state = self
            .state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695043928968174);
        self.state
    }
    fn next_f64(&mut self) -> f64 {
        (self.next() >> 11) as f64 / (1u64 << 53) as f64
    }
}

/// Generate a doc comment patch for a file
fn generate_doc_patch(_file_path: &str, seed: usize) -> String {
    format!(
        "/// Doc patch {}: Adds documentation for the module\n///\n/// This is a test patch generated by the NPE upgrade loop.\n",
        seed
    )
}

/// Apply a patch to a file
fn apply_patch(file_path: &str, patch_text: &str) -> Result<String, String> {
    // First read original
    let original = fs::read_to_string(file_path)
        .map_err(|e| format!("Failed to read {}: {}", file_path, e))?;

    // Create backup
    let backup_path = format!("{}.bak", file_path);
    fs::write(&backup_path, &original).map_err(|e| format!("Failed to backup: {}", e))?;

    // Prepend patch to file start
    let new_content = format!("{}{}", patch_text, original);
    fs::write(file_path, new_content).map_err(|e| format!("Failed to write: {}", e))?;

    Ok(backup_path)
}

/// Restore original from backup
fn restore_backup(file_path: &str) -> Result<(), String> {
    let backup_path = format!("{}.bak", file_path);
    if Path::new(&backup_path).exists() {
        let content = fs::read_to_string(&backup_path)
            .map_err(|e| format!("Failed to read backup: {}", e))?;
        fs::write(file_path, content).map_err(|e| format!("Failed to restore: {}", e))?;
        fs::remove_file(&backup_path).map_err(|e| format!("Failed to remove backup: {}", e))?;
    }
    Ok(())
}

/// Verify a code patch using cargo check
fn verify_patch(_file_path: &str) -> (bool, String) {
    let output = Command::new("cargo")
        .args(["check", "-p", "coh-genesis"])
        .current_dir(".")
        .output();

    match output {
        Ok(o) => {
            if o.status.success() {
                (true, "cargo check passed".to_string())
            } else {
                let err = String::from_utf8_lossy(&o.stderr);
                (false, format!("cargo check failed: {}", err))
            }
        }
        Err(e) => (false, format!("Failed to run cargo: {}", e)),
    }
}

fn apply_toml_patch(file_path: &str, crate_name: &str, old_v: &str, new_v: &str) -> Result<String, String> {
    let original = fs::read_to_string(file_path)
        .map_err(|e| format!("Failed to read {}: {}", file_path, e))?;

    let backup_path = format!("{}.bak", file_path);
    fs::write(&backup_path, &original).map_err(|e| format!("Failed to backup: {}", e))?;

    let target_str = format!("{} = \"{}\"", crate_name, old_v);
    let replace_str = format!("{} = \"{}\"", crate_name, new_v);
    
    // Fallback target for objects
    let target_str_obj = format!("version = \"{}\"", old_v);
    let replace_str_obj = format!("version = \"{}\"", new_v);

    let new_content = if original.contains(&target_str) {
        original.replace(&target_str, &replace_str)
    } else if original.contains(crate_name) && original.contains(&target_str_obj) {
        original.replace(&target_str_obj, &replace_str_obj)
    } else {
        // Just append if not found for testing
        format!("{}\n{} = \"{}\"\n", original, crate_name, new_v)
    };

    fs::write(file_path, new_content).map_err(|e| format!("Failed to write: {}", e))?;
    Ok(backup_path)
}

fn verify_dep_upgrade(crate_dir: &str) -> (bool, String) {
    let output = Command::new("cargo")
        .args(["update", "--dry-run"])
        .current_dir(crate_dir)
        .output();

    match output {
        Ok(o) => {
            if o.status.success() {
                // Also check if it builds
                let check = Command::new("cargo").args(["check"]).current_dir(crate_dir).output();
                if let Ok(c) = check {
                    if c.status.success() {
                        return (true, "cargo update and check passed".to_string());
                    }
                }
                (false, "cargo check failed after update".to_string())
            } else {
                let err = String::from_utf8_lossy(&o.stderr);
                (false, format!("cargo update failed: {}", err))
            }
        }
        Err(e) => (false, format!("Failed to run cargo: {}", e)),
    }
}

fn main() {
    use coh_genesis::phaseloom_lite::{PhaseLoomConfig, PhaseLoomState, BoundaryReceiptSummary};
    use coh_genesis::code_patch::{UpgradeTarget, UpgradeClass, DependencyUpgradeCandidate, DependencyUpgradeReport, is_upgrade_admissible};

    println!("NPE Rust Upgrade Loop - Mixed Mode (Live Files)");
    println!("===============================================");
    println!();

    let test_file = "crates/coh-genesis/src/candidate.rs";
    let cargo_file = "crates/coh-genesis/Cargo.toml";
    let mut rng = SimpleRng::new(42);

    let config = PhaseLoomConfig::default();
    let mut state = PhaseLoomState::new(&config);

    let mut code_success = 0;
    let mut dep_success = 0;

    for step in 1..=4 {
        let mode = if step % 2 != 0 { UpgradeTarget::CodePatch } else { UpgradeTarget::Dependency };
        
        match mode {
            UpgradeTarget::CodePatch => {
                println!("Step {}: [CodePatch Mode]", step);
                let patch_text = generate_doc_patch(test_file, step);
                let _backup = apply_patch(test_file, &patch_text).unwrap();
                
                let (verified, _) = verify_patch(test_file);
                let _ = restore_backup(test_file);

                // Ingest receipt
                let receipt = BoundaryReceiptSummary {
                    domain: "code".to_string(),
                    target: test_file.to_string(),
                    strategy_class: "CodePatch".to_string(),
                    accepted: verified,
                    outcome: if verified { "accepted".to_string() } else { "rejected".to_string() },
                    novelty: 0.5,
                    ..BoundaryReceiptSummary::default()
                };
                state.ingest(&receipt, &config);
                
                if verified { code_success += 1; }
                println!("  Result: {} | PhaseLoom weight(CodePatch) = {:.2}", 
                         if verified { "ACCEPTED" } else { "REJECTED" },
                         state.weight_for("CodePatch"));
            },
            UpgradeTarget::Dependency => {
                println!("Step {}: [Dependency Mode]", step);
                let crate_name = "serde_json";
                let old_v = "1.0.114";
                let new_v = "1.0.115";
                
                // Construct Candidate
                let candidate = DependencyUpgradeCandidate {
                    id: format!("dep-{}", step),
                    wildness: 0.3,
                    upgrade_class: UpgradeClass::VersionBump,
                    cargo_toml_path: cargo_file.to_string(),
                    upgrade_text: format!("{} {} -> {}", crate_name, old_v, new_v),
                    old_version: old_v.to_string(),
                    new_version: new_v.to_string(),
                    crate_name: crate_name.to_string(),
                    novelty: 0.8,
                };
                
                let _backup = apply_toml_patch(cargo_file, crate_name, old_v, new_v).unwrap();
                let (verified, _) = verify_dep_upgrade("crates/coh-genesis");
                let _ = restore_backup(cargo_file);
                
                // Simulate admissibility report
                let report = DependencyUpgradeReport {
                    cargo_update_dry_run_pass: verified,
                    cargo_check_pass: verified,
                    outdated_check_pass: true,
                    breaking_change: false,
                    new_version_available: true,
                    update_size_kb: 1,
                    upgrade_margin: 50,
                };
                
                let (admissible, _) = is_upgrade_admissible(&candidate, &report, 500);

                // Ingest receipt
                let receipt = BoundaryReceiptSummary {
                    domain: "dependency".to_string(),
                    target: cargo_file.to_string(),
                    strategy_class: "VersionBump".to_string(),
                    accepted: admissible && verified,
                    outcome: if admissible && verified { "accepted".to_string() } else { "rejected".to_string() },
                    novelty: 0.8,
                    ..BoundaryReceiptSummary::default()
                };
                state.ingest(&receipt, &config);
                
                if admissible && verified { dep_success += 1; }
                println!("  Result: {} | PhaseLoom weight(VersionBump) = {:.2}", 
                         if admissible && verified { "ACCEPTED" } else { "REJECTED" },
                         state.weight_for("VersionBump"));
            },
            _ => {}
        }
    }

    println!("\nSUCCESS: Mixed Upgrade Loop Completed");
    println!("  Code Patches Verified: {}/2", code_success);
    println!("  Dep Upgrades Verified: {}/2", dep_success);
    println!("  PhaseLoom final weights:");
    for (strategy, weight) in state.all_weights() {
        println!("    - {}: {:.3}", strategy, weight);
    }
}
